apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: credit-api
  labels:
    release: kps
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: credit-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
