{
 "title": "Credit Scoring / API",
 "tags": [
  "credit-scoring",
  "fastapi"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "UP",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "up{job=~\".*credit-scoring-api.*\"}"
    }
   ]
  },
  {
   "title": "Requests / sec",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=~\".*credit-scoring-api.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "5xx / sec",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 4, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=~\".*credit-scoring-api.*\",status=~\"5..\"}[1m]))"
    }
   ]
  }
 ]
}